import pool from "./index";

const ensureCapsuleTimestamps = async () => {
  await pool.query(`
    UPDATE capsules
    SET created_at = COALESCE(created_at, now()),
        updated_at = COALESCE(updated_at, now())
    WHERE created_at IS NULL
       OR updated_at IS NULL;
  `);

  await pool.query(`
    ALTER TABLE capsules
      ALTER COLUMN created_at SET DEFAULT now(),
      ALTER COLUMN updated_at SET DEFAULT now(),
      ALTER COLUMN created_at SET NOT NULL,
      ALTER COLUMN updated_at SET NOT NULL;
  `);
};

const ensureMessageIdIdentity = async () => {
  const { rows } = await pool.query<{
    is_identity: "YES" | "NO";
  }>(`
    SELECT is_identity
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'messages'
      AND column_name = 'id';
  `);

  if (rows[0]?.is_identity !== "YES") {
    await pool.query(`
      ALTER TABLE messages
      ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
    `);
  }

  await pool.query(`
    SELECT setval(
      pg_get_serial_sequence('messages', 'id'),
      GREATEST(COALESCE((SELECT MAX(id) FROM messages), 0) + 1, 1),
      false
    );
  `);
};

const ensureMessageCreatedAt = async () => {
  await pool.query(`
    UPDATE messages
    SET created_at = COALESCE(created_at, now())
    WHERE created_at IS NULL;
  `);

  await pool.query(`
    ALTER TABLE messages
      ALTER COLUMN created_at SET DEFAULT now(),
      ALTER COLUMN created_at SET NOT NULL;
  `);
};

export const ensureDatabaseSchema = async () => {
  await ensureCapsuleTimestamps();
  await ensureMessageIdIdentity();
  await ensureMessageCreatedAt();
};
