CREATE TABLE "capsules" (
	"id" char(26) PRIMARY KEY NOT NULL,
	"slug" varchar(50) NOT NULL,
	"title" varchar(100) NOT NULL,
	"open_at" timestamp with time zone NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	"password_hash" varchar(255) NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "messages" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "messages_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"capsule_id" char(26) NOT NULL,
	"nickname" varchar(20) NOT NULL,
	"content" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "messages" ADD CONSTRAINT "messages_capsule_id_capsules_id_fk" FOREIGN KEY ("capsule_id") REFERENCES "public"."capsules"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "capsules_slug_unq" ON "capsules" USING btree ("slug");--> statement-breakpoint
CREATE INDEX "capsules_expires_at_idx" ON "capsules" USING btree ("expires_at");--> statement-breakpoint
CREATE UNIQUE INDEX "messages_capsule_id_nickname_unq" ON "messages" USING btree ("capsule_id","nickname");--> statement-breakpoint
CREATE INDEX "messages_capsule_id_id_idx" ON "messages" USING btree ("capsule_id","id");