-- Reference-only schema snapshot
-- Source of truth: src/db/schema.ts + drizzle migrations
-- Do not apply this file directly. Use Drizzle migration commands instead.

CREATE TABLE "capsules" (
	"id" char(26) PRIMARY KEY,
	"slug" varchar(50) NOT NULL,
	"title" varchar(100) NOT NULL,
	"open_at" timestamp with time zone NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	"version" integer DEFAULT 1 NOT NULL,
	"password_hash" varchar(255) NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE "messages" (
	"id" bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "messages_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1),
	"capsule_id" char(26) NOT NULL,
	"nickname" varchar(20) NOT NULL,
	"content" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);

CREATE UNIQUE INDEX "capsules_slug_unq" ON "capsules" ("slug");
CREATE INDEX "capsules_expires_at_idx" ON "capsules" ("expires_at");
CREATE UNIQUE INDEX "messages_capsule_id_nickname_unq" ON "messages" ("capsule_id","nickname");
CREATE INDEX "messages_capsule_id_id_idx" ON "messages" ("capsule_id","id");
ALTER TABLE "messages" ADD CONSTRAINT "messages_capsule_id_capsules_id_fkey" FOREIGN KEY ("capsule_id") REFERENCES "capsules"("id") ON DELETE CASCADE;
