-- Capsules Table
CREATE TABLE capsules (
    id             char(26)      NOT NULL,
    slug           varchar(50)   NOT NULL,
    title          varchar(100)  NOT NULL,
    open_at        timestamptz   NOT NULL,
    expires_at     timestamptz   NOT NULL,
    password_hash  varchar(255)  NOT NULL,
    created_at     timestamptz   NOT NULL DEFAULT now(),
    updated_at     timestamptz   NOT NULL DEFAULT now(),
    CONSTRAINT pk_capsules PRIMARY KEY (id),
    CONSTRAINT capsules_slug_unq UNIQUE (slug)
);
-- expires_at 조회할 사항이 많기 때문에 index 걸기 & 캡슐 만료일 조회 성능 최적화
CREATE INDEX capsules_expires_at_idx ON capsules (expires_at);

-- Messages Table
CREATE TABLE messages (
    id          bigint        GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    capsule_id  char(26)      NOT NULL,
    nickname    varchar(20)   NOT NULL,
    content     text          NOT NULL,
    created_at  timestamptz   NOT NULL DEFAULT now(),
    CONSTRAINT pk_messages PRIMARY KEY (id)
);
-- 같은 캡슐(capsule_id) 내에서 닉네임(nickname) 중복 방지
CREATE UNIQUE INDEX messages_capsule_id_nickname_unq
ON messages (capsule_id, nickname);

-- 특정 캡슐 내 메시지 목록 조회 성능 최적화 (정렬 포함)
CREATE INDEX messages_capsule_id_id_idx ON messages (capsule_id, id ASC);

-- Foreign Key Constraints
ALTER TABLE messages 
ADD CONSTRAINT messages_capsule_id_capsules_id_fk
FOREIGN KEY (capsule_id) REFERENCES capsules (id)
ON DELETE CASCADE;
