name: Render Keep Alive Production

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  ping-server:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      - name: Execute Health Check Request
        run: |
          curl -f -s -S -m 120 \
          --retry 3 \
          --retry-delay 5 \
          --retry-connrefused \
          -A "GitHubActions-KeepAlive-Bot/1.0" \
          ${{ secrets.RENDER_HEALTH_CHECK_URL }}